# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '1.0'

#create a volume for the my sql container.To ensure Data persists after my sql container is stopped
volumes:
  db:
    driver: local

services:
  #DataBase Service
  db:
    #Pull the latest mysql image
    image: mysql:8.0.32
    #Map port 3306 on the mysql container to port 3306 in the host
    ports:
      - "3306:3306"
    #prevent warning-insecure-configuration-for-pid-file in /var/run/mysqld
    #Specify where the persisted data should be stored
    volumes:
      - db:/var/lib/mysql
      - "./db/init.sql:/docker-entrypoint-initdb.d/init.sql"
    restart: always
    #Specify Environment Variables for mysql
    environment: 
      MYSQL_ROOT_PASSWORD: ZwarteRidder007
      MYSQL_USER: lvoo
      MYSQL_PASSWORD: pass@word1234
      MYSQL_DATABASE: theplacetomeet
  #Api  Service
  api:
    build:
      context: .
      #Use the DockerFile in that Directory
      dockerfile: Dockerfile
    #This Service Depends on the database service specifed above
    depends_on: 
      - db
    ports:
      - "5204:5204"
      - "7045:7045"
    restart: always
    #Specify Environment Variables for the Api Service
    environment: 
      - DBHOST=db
      - ASPNETCORE_ENVIRONMENT=Development
    #  - ASPNETCORE_URLS=http://+:5204;https://+:7045
      - ASPNETCORE_URLS=http://+:5204
    #  - ASPNETCORE_Kestrel__Certificates__Default__Password=ZwarteRidder007
    #  - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/servercert.pfx
  client:   
    container_name: docker-react-client
    image: docker-react-image
    build: 
      context: ./Apps/theplacetomeet.react.app
      dockerfile: Dockerfile.client
    ports:
      -  "3000:80"